//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hb.HexEditor2 {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hb.HexEditor2.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Byte {0} benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Byte {
            get {
                return ResourceManager.GetString("Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ContextMenuCopy {
            get {
                return ResourceManager.GetString("ContextMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ContextMenuCut {
            get {
                return ResourceManager.GetString("ContextMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ContextMenuPaste {
            get {
                return ResourceManager.GetString("ContextMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ContextMenuSelectAll {
            get {
                return ResourceManager.GetString("ContextMenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file does not exist! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find reached end of file! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FindOperationEndOfFile {
            get {
                return ResourceManager.GetString("FindOperationEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   German benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No byte is selected benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoByteSelected {
            get {
                return ResourceManager.GetString("NoByteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is locked by another process and cannot be opened! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpenFailed {
            get {
                return ResourceManager.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is locked. Do you want to open it in read-only mode? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpenReadonly {
            get {
                return ResourceManager.GetString("OpenReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program restart required for settings to take affect! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProgramRestartSettings {
            get {
                return ResourceManager.GetString("ProgramRestartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///    [read-only] benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Readonly {
            get {
                return ResourceManager.GetString("Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Russian benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save changes? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simplified Chinese benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SimplifiedChinese {
            get {
                return ResourceManager.GetString("SimplifiedChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turkish benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
    }
}
